spring:
  data:
    mongodb:
      database: morphia

      # Optional [Add these only if your MongoDB instance is secured]
      # authentication-database: some-database
      username: masiv
      password: masiv